import {
  Home,
  LoginPage,
  OverviewPage,
  OverviewYouthUnionPage,
  UnionBaseInfoPage,
  UnionClubInfoPage,
  GeneralAnnoucementPage,
  DetailNewsPage,
  CreateNewsPage,
  NotFoundPage,
  GeneralActivityPage,
  DetailActivityPage,
  CreateActivity,
  InformationUserPage,
  DashboardAdmin,
  StudentActivityPage,
  EditNewsAdminPage,
  EditUsersAdminPage,
  ManageRequestPage,
  EditNewsForUnionPage,
  EditActivityPage,
  EditInforAdminPage,
  AddUserAdminPage,
  ChangePasswordAdminPage,
} from '../pages'

const ROUTES = [
  {
    path: '/',
    name: 'Home Page',
    exact: true,
    component: Home,
  },
  {
    path: '/login',
    name: 'Login Page',
    exact: true,
    component: LoginPage,
  },
  {
    path: '/overview',
    name: 'Login Page',
    exact: true,
    component: OverviewPage,
  },
  {
    path: '/overview/youthunion',
    name: 'OverviewYouthUnionPagein Page',
    exact: true,
    component: OverviewYouthUnionPage,
  },
  {
    path: '/overview/baseinfo',
    name: 'UnionBaseInfoPage Page',
    exact: true,
    component: UnionBaseInfoPage,
  },
  {
    path: '/overview/baseinfo',
    name: 'UnionBaseInfoPage Page',
    exact: true,
    component: UnionBaseInfoPage,
  },
  {
    path: '/overview/clubinfo',
    name: 'UnionClubInfoPage Page',
    exact: true,
    component: UnionClubInfoPage,
  },
  {
    path: '/general',
    name: 'GeneralAnnoucementPage Page',
    exact: true,
    component: GeneralAnnoucementPage,
  },
  {
    path: '/news/:slug',
    name: 'Detail News Page',
    exact: true,
    component: DetailNewsPage,
  },
  {
    path: '/general/:slug',
    name: 'Detail News Page',
    exact: true,
    component: GeneralAnnoucementPage,
  },
  {
    path: '/create',
    name: 'Create News Page',
    exact: true,
    component: CreateNewsPage,
  },
  // Activity
  {
    path: '/activity',
    name: 'GeneralActivity Page',
    exact: true,
    component: GeneralActivityPage,
  },
  {
    path: '/general-activity/:slug',
    name: 'Detail Activity Page',
    exact: true,
    component: GeneralActivityPage,
  },
  {
    path: '/activity/:slug',
    name: 'Detail Activity Page',
    exact: true,
    component: DetailActivityPage,
  },
  {
    path: '/create-activity',
    name: 'Create Activity',
    exact: true,
    component: CreateActivity,
  },
  {
    path: '/info',
    name: 'Information',
    exact: true,
    component: InformationUserPage,
  },
  {
    path: '/request-news',
    name: 'Manage Request News',
    exact: true,
    component: ManageRequestPage,
  },
  {
    path: '/edit-request/:slug',
    name: 'Edit request news',
    exact: true,
    component: EditNewsForUnionPage,
  },
  {
    path: '/dashboard/request-news/:slug',
    name: 'Information',
    exact: false,
    component: EditNewsAdminPage,
  },
  {
    path: '/dashboard/create-user',
    name: 'Create User',
    exact: false,
    component: AddUserAdminPage,
  },
  {
    path: '/dashboard/news/:slug',
    name: 'Information',
    exact: false,
    component: EditNewsAdminPage,
  },
  {
    path: '/student-activity',
    name: 'Student Activity',
    exact: true,
    component: StudentActivityPage,
  },
  // Admin
    {
    path: '/dashboard/activity/request-activity/:slug',
    name: 'Edit Activity Page',
    exact: false,
    component: EditActivityPage,
  },
  {
    path: '/dashboard/activity/editActivity/:slug',
    name: 'Edit Activity Page',
    exact: false,
    component: EditActivityPage,
  },
  {
    path: '/dashboard/infor-admin',
    name: 'Edit Infor Admin Page',
    exact: true,
    component: EditInforAdminPage,
  },
  {
    path: '/dashboard/change-password-admin',
    name: 'Change Password Admin Page',
    exact: true,
    component: ChangePasswordAdminPage,
  },

  {
    path: '/dashboard/edit-users/:idUser',
    name: 'Edit User Admin',
    exact: false,
    component: EditUsersAdminPage,
  },
  {
    path: '/dashboard',
    name: 'Information',
    exact: false,
    component: DashboardAdmin,
  },
  {
    path: '*',
    exact: false,
    component: NotFoundPage,
  },
]

export default ROUTES
